version: '3'
networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.1/24
    
services:
    identitydb:
        image: identitydb
        build: ./Services/IdentityService/db
        networks:
            - default
        volumes:
            - pgdata:/pgdata
        ports: 
            - "5432:5432"
        environment: 
            - POSTGRES_USER=docker
            - POSTGRES_PASSWORD=docker
            - POSTGRES_DB=identity
            - PGDATA=/pgdata
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -h postgres-host -p 5432 -U postgres"]
            interval: 5s
            timeout: 5s
            retries: 5

    identity:
        image: identity
        build: ./Services/IdentityService/src
        networks:
            - default      
        ports:
            - "8000:8000"
        depends_on:
            - identitydb
        #command: ["./wait-for-postgres.sh", "identitydb:5432", "node", "server.js"]
    
    catalogdb:
        image: catalogdb
        build: ./Services/CatalogService/db
        networks: 
            - default
        ports:
            - '27017:27017'
        volumes:
            - catalogdata:/data/db
    catalog:
        image: catalog
        build: ./Services/CatalogService/src
        networks: 
            - default
        ports:
            - "8081:8081"
        depends_on: 
            - catalogdb
    stock:
        image: stock
        build: ./Services/StockService/src
        networks: 
            - default
        ports: 
            - "8083:8083"


    websitegw:
        image: websitegw
        build: ./Gateway/website/src
        networks: 
            - default
        ports: 
            - "3000:3000"
        depends_on: 
            - catalog
            - stock

    website:
        image: website
        build: ./Web/WebSite
        networks: 
            - default
        ports: 
            - "8082:8082"
        depends_on: 
            - websitegw
volumes: 
    pgdata:
        driver: local
    catalogdata:
        driver: local

