version: '3'
networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.1/24
    
services:
    identitydb:
        image: identitydb
        build: ./Services/IdentityService/db
        networks:
            - default
        volumes:
            - pgdata:/pgdata
        ports: 
            - "5432:5432"
        environment: 
            - POSTGRES_USER=docker
            - POSTGRES_PASSWORD=docker
            - POSTGRES_DB=identity
            - PGDATA=/pgdata
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -h postgres-host -p 5432 -U postgres"]
            interval: 5s
            timeout: 5s
            retries: 5

    identity:
        image: identity
        build: ./Services/IdentityService/src
        networks:
            - default      
        ports:
            - "8000:8000"
        depends_on:
            - identitydb
        #command: ["./wait-for-postgres.sh", "identitydb:5432", "node", "server.js"]

    #gatewaydb:
        #image: gatewaydb
        #build: ./Gateway/db
        #networks: 
            #- default
        #volumes:
            #- data:/data
        #ports:
            #- "6379:6379"
        
    #gateway: 
        #image: gateway
        #build: ./Gateway/src
        #networks: 
            #- default
        #ports:
            #- "8080:8080"
            #- "8443:8443"
            #- "9876:9876"
        #depends_on: 
            #- gatewaydb
volumes: 
    pgdata:
        driver: local
    #data:
        #driver: local

